name: $(Build.BuildId)
trigger:
  # This is where pull requests from "bors r+" are built.
  - staging
  # This is where pull requests from "bors try" are built.
  - trying
  # Always build master
  - master
pr:
  # Enable building pull requests.
  - master
stages:
  - stage: Testing
    jobs:
      - job:
        variables:
          rust: 1.46.0
        strategy:
          matrix:
            MinGW 32-bit:
              image: vs2017-win2016
              target: i686-pc-windows-gnu
            MinGW 64-bit:
              image: vs2017-win2016
              target: x86_64-pc-windows-gnu
        pool:
          vmImage: $(image)
        steps:
          - checkout: self
            fetchDepth: 1
            path: clap
            displayName: Checkout repository
          - script: rustup default $(rust)-$(target)
            displayName: Install rust
          - script: cargo test --no-default-features --features "std cargo" -p clap:3.0.0-beta.2
            displayName: Test with almost no features
          - script: cargo test --features "yaml"
            displayName: Test with most features
