msrv = "1.64.0"  # MSRV
warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
disallowed-methods = [
    { path = "std::option::Option::map_or", reason = "use `map(..).unwrap_or(..)`" },
    { path = "std::option::Option::map_or_else", reason = "use `map(..).unwrap_or_else(..)`" },
    { path = "std::result::Result::map_or", reason = "use `map(..).unwrap_or(..)`" },
    { path = "std::result::Result::map_or_else", reason = "use `map(..).unwrap_or_else(..)`" },
]
