[package]
name = "clap_derive"
version = "3.0.0-beta.1"
edition = "2018"
authors = [
	"Guillaume Pinot <texitoi@texitoi.eu>",
	"Clap Maintainers"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]
description = "Parse command line argument by defining a struct, derive crate."
repository = "https://github.com/clap-rs/clap/tree/master/clap_derive"
documentation = "https://docs.rs/clap_derive"
homepage = "https://clap.rs/"
keywords = [
	"clap",
	"cli",
	"parse",
	"derive",
	"proc_macro"
]
categories = ["command-line-interface", "development-tools::procedural-macro-helpers"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[badges]
is-it-maintained-issue-resolution = { repository = "clap-rs/clap" }
is-it-maintained-open-issues = { repository = "clap-rs/clap" }
maintenance = {status = "actively-developed"}

[lib]
proc-macro = true
bench = false

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
heck = "0.3.0"
proc-macro-error = "1"

[dev-dependencies]
clap = { path = "../" }
trybuild = "1.0"
rustversion = "1"
version-sync = "0.8"

[features]
default = []
unstable = []
debug = []
doc = []

[package.metadata.docs.rs]
features = ["doc"]
targets = ["x86_64-unknown-linux-gnu"]
