environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

test_script:
  - cargo test